### ISSUE TITLE
生成的正交表试验次数偏多，请问有没有办法强制生成null列

### ISSUE THREAD

**Issue by TouchDeeper** [lovesoo/OrthogonalArrayTest#1]
您好，

感谢您的工作，我有几个问题想请教下。
1.我在测试的时候发现该程序生成的正交表试验次数偏多，不过只要是正交的感觉也问题不大。
2.空列可以用来计算试验误差，但是有的情况下并没有办法生成空列，感觉这个问题比较麻烦。
我的测试用例是
```
    case1 = OrderedDict([('A', [1, 2]),
                         ('B', [1, 2]),
                         ('AXB', [1, 2]),
                         ('C', [1, 2]),
                         ('AXC', [1, 2]),
                         ('BXC', [1, 2])
                         ])

```
下面是我用软件手动选表L8(2^7)生成的正交表：
![image](https://user-images.githubusercontent.com/39310744/65814734-394dc000-e218-11e9-94e9-79d6f20e692f.png)

**Comment by lovesoo** [comment]
1）null列不是强制生成的，目前我用的数据来源是 SAS 提供：
　　http://support.sas.com/techsup/technote/ts723_Designs.txt

2）你所列的示例中其实是匹配到了 2^11     n=12 这个正交表，裁剪处理后得到12条数据

整体可能算法还需优化。

**Comment by TouchDeeper** [comment]
貌似我可以手动给空列，就当成是一个因素，你觉得如何？

**Comment by lovesoo** [comment]
如果你手工把 None 作为一个因素的话，那肯定是可以的。

**Comment by TouchDeeper** [comment]
好的，谢谢你啦

**Comment by TouchDeeper** [comment]
你好，关于正交表有问题想请教下
1.对于水平数不同的情况下，会生成null水平，这种情况该因素怎么给值合适呢？把水平平均给所有的null合适吗？
2.对于交互列的组合不知道怎么操作，比如A有6个水平，B有6个水平，AXB应该有多少水平，怎么组合？
