### ISSUE TITLE
为什么 有些 设计点的取值为null

### ISSUE THREAD

**Issue by bugatti742** [lovesoo/OrthogonalArrayTest#2]

**Comment by ghost** [comment]
贴出你的输入呀！推测输入没有按 因素的水平数量 从小到大排序后 传入。例如：
case1 = OrderedDict([('K2', [1, 2]), ('K3', [1, 2]), ('K1', [1, 2, 3, 4, 5, 6])]) 【没问题】
case2 = OrderedDict([('K1', [1, 2, 3, 4, 5, 6]), ('K2', [1, 2]), ('K3', [1, 2])])  【有问题】

**Comment by lovesoo** [comment]
> 贴出你的输入呀！推测输入没有按 因素的水平数量 从小到大排序后 传入。例如： case1 = OrderedDict([('K2', [1, 2]), ('K3', [1, 2]), ('K1', [1, 2, 3, 4, 5, 6])]) 【没问题】 case2 = OrderedDict([('K1', [1, 2, 3, 4, 5, 6]), ('K2', [1, 2]), ('K3', [1, 2])]) 【有问题】

已增加根据因素水平数量进行自动排序的功能

**Comment by ghost** [comment]
昨天我也在加这个，忘记给你提pr了XD

**Comment by lovesoo** [comment]
> 昨天我也在加这个，忘记给你提pr了XD

下次先提PR ^_^
